// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (C) 2026 Teqpace Services Ltd.
//
// This file is part of Isopace, a financial transaction framework.
//
// Isopace is dual-licensed:
//   - under the GNU Affero General Public License v3.0 or later (see LICENSE); or
//   - under a commercial license from Teqpace Services Ltd. (see COMMERCIAL-LICENSE.md).
//
// Authorship is recorded in the AUTHORS file.

package packager

import (
	"github.com/teqpace-services/isopace/fieldcodec"
	"github.com/teqpace-services/isopace/iso8583"
)

// zonePackager is the "zone" profile: a full ISO 8583:1987 directory (DE 0..128)
// with an ASCII-numeric MTI, a binary message bitmap, and the DE 127
// reserved-private subfield group. Numerics are ASCII digits, amounts are kept
// as fixed text (they carry a leading credit/debit sign), and the two binary
// disciplines are raw octets and ASCII hex.
var zonePackager = concretePackager{
	id:     "zone",
	mti:    fieldcodec.NumASCII,
	bitmap: fieldcodec.BitmapBinary,
	fields: zoneFields,
	sub127: &zoneSub127,
}

var zoneFields = []field{
	{2, "PAN - PRIMARY ACCOUNT NUMBER", numeric, llVar, 19},
	{3, "PROCESSING CODE", numeric, fixedWidth, 6},
	{4, "AMOUNT, TRANSACTION", numeric, fixedWidth, 12},
	{5, "AMOUNT, SETTLEMENT", numeric, fixedWidth, 12},
	{6, "AMOUNT, CARDHOLDER BILLING", numeric, fixedWidth, 12},
	{7, "TRANSMISSION DATE AND TIME", numeric, fixedWidth, 10},
	{8, "Cardholder billing fee amount", numeric, fixedWidth, 8},
	{9, "CONVERSION RATE, SETTLEMENT", numeric, fixedWidth, 8},
	{10, "Cardholder billing conversion rate", numeric, fixedWidth, 8},
	{11, "SYSTEM TRACE AUDIT NUMBER", numeric, fixedWidth, 6},
	{12, "TIME, LOCAL TRANSACTION", numeric, fixedWidth, 6},
	{13, "DATE, LOCAL TRANSACTION", numeric, fixedWidth, 4},
	{14, "DATE, EXPIRATION", numeric, fixedWidth, 4},
	{15, "DATE, SETTLEMENT", numeric, fixedWidth, 4},
	{16, "DATE, CONVERSION", numeric, fixedWidth, 4},
	{17, "DATE, CAPTURE", numeric, fixedWidth, 4},
	{18, "MERCHANTS TYPE", numeric, fixedWidth, 4},
	{19, "Acquiring institution country code", numeric, fixedWidth, 3},
	{20, "Primary account number country code", numeric, fixedWidth, 3},
	{21, "Forwarding institution country code", numeric, fixedWidth, 3},
	{22, "POINT OF SERVICE ENTRY MODE", numeric, fixedWidth, 3},
	{23, "CARD SEQUENCE NUMBER", numeric, fixedWidth, 3},
	{24, "Network international identifier", numeric, fixedWidth, 3},
	{25, "POINT OF SERVICE CONDITION CODE", numeric, fixedWidth, 2},
	{26, "POINT OF SERVICE PIN CAPTURE CODE", numeric, fixedWidth, 2},
	{27, "AUTHORIZATION IDENTIFICATION RESP LEN", numeric, fixedWidth, 1},
	{28, "AMOUNT, TRANSACTION FEE", textual, fixedWidth, 9},
	{29, "AMOUNT, SETTLEMENT FEE", textual, fixedWidth, 9},
	{30, "AMOUNT, TRANSACTION PROCESSING FEE", textual, fixedWidth, 9},
	{31, "AMOUNT, SETTLEMENT PROCESSING FEE", textual, fixedWidth, 9},
	{32, "ACQUIRING INSTITUTION IDENT CODE", numeric, llVar, 11},
	{33, "FORWARDING INSTITUTION IDENT CODE", numeric, llVar, 11},
	{34, "Extended primary account number", numeric, llVar, 28},
	{35, "TRACK 2 DATA", numeric, llVar, 37},
	{36, "TRACK 3 DATA", numeric, lllVar, 104},
	{37, "RETRIEVAL REFERENCE NUMBER", textual, fixedWidth, 12},
	{38, "AUTHORIZATION IDENTIFICATION RESPONSE", textual, fixedWidth, 6},
	{39, "RESPONSE CODE", textual, fixedWidth, 2},
	{40, "SERVICE RESTRICTION CODE", textual, fixedWidth, 3},
	{41, "CARD ACCEPTOR TERMINAL IDENTIFICACION", textual, fixedWidth, 8},
	{42, "CARD ACCEPTOR IDENTIFICATION CODE", textual, fixedWidth, 15},
	{43, "CARD ACCEPTOR NAME/LOCATION", textual, fixedWidth, 40},
	{44, "ADITIONAL RESPONSE DATA", textual, llVar, 25},
	{45, "TRACK 1 DATA", textual, llVar, 76},
	{46, "Additional data - ISO", textual, lllVar, 999},
	{47, "Additional data - national", textual, lllVar, 999},
	{48, "ADITIONAL DATA - PRIVATE", textual, lllVar, 999},
	{49, "CURRENCY CODE, TRANSACTION", textual, fixedWidth, 3},
	{50, "CURRENCY CODE, SETTLEMENT", textual, fixedWidth, 3},
	{51, "Cardholder billing currency code", textual, fixedWidth, 3},
	{52, "PIN DATA", binary, fixedWidth, 8},
	{53, "SECURITY RELATED CONTROL INFORMATION", binary, fixedWidth, 48},
	{54, "ADDITIONAL AMOUNTS", textual, lllVar, 120},
	{55, "Reserved for ISO use", textual, lllVar, 999},
	{56, "RESERVED ISO", textual, lllVar, 999},
	{57, "RESERVED NATIONAL", textual, fixedWidth, 3},
	{58, "RESERVED NATIONAL", textual, lllVar, 11},
	{59, "RESERVED NATIONAL", textual, lllVar, 999},
	{60, "RESERVED PRIVATE", textual, lllVar, 999},
	{61, "RESERVED PRIVATE", textual, lllVar, 999},
	{62, "RESERVED PRIVATE", textual, lllVar, 999},
	{63, "RESERVED PRIVATE", textual, lllVar, 999},
	{64, "RESERVED PRIVATE", binary, fixedWidth, 8},
	{65, "RESERVED PRIVATE", binary, fixedWidth, 8},
	{66, "SETTLEMENT CODE", numeric, fixedWidth, 1},
	{67, "EXTENDED PAYMENT CODE", numeric, fixedWidth, 2},
	{68, "Receiving institution country code", numeric, fixedWidth, 3},
	{69, "SETTLEMENT INSTITUTION COUNTRY CODE", numeric, fixedWidth, 3},
	{70, "NETWORK MANAGEMENT INFORMATION CODE", numeric, fixedWidth, 3},
	{71, "MESSAGE NUMBER", numeric, fixedWidth, 4},
	{72, "LAST MESSAGE NUMBER", numeric, fixedWidth, 4},
	{73, "DATE ACTION", numeric, fixedWidth, 6},
	{74, "CREDITS NUMBER", numeric, fixedWidth, 10},
	{75, "CREDITS REVERSAL NUMBER", numeric, fixedWidth, 10},
	{76, "DEBITS NUMBER", numeric, fixedWidth, 10},
	{77, "DEBITS REVERSAL NUMBER", numeric, fixedWidth, 10},
	{78, "TRANSFER NUMBER", numeric, fixedWidth, 10},
	{79, "TRANSFER REVERSAL NUMBER", numeric, fixedWidth, 10},
	{80, "INQUIRIES NUMBER", numeric, fixedWidth, 10},
	{81, "AUTHORIZATION NUMBER", numeric, fixedWidth, 10},
	{82, "CREDITS, PROCESSING FEE AMOUNT", numeric, fixedWidth, 12},
	{83, "CREDITS, TRANSACTION FEE AMOUNT", numeric, fixedWidth, 12},
	{84, "DEBITS, PROCESSING FEE AMOUNT", numeric, fixedWidth, 12},
	{85, "DEBITS, TRANSACTION FEE AMOUNT", numeric, fixedWidth, 12},
	{86, "CREDITS, AMOUNT", numeric, fixedWidth, 16},
	{87, "CREDITS, REVERSAL AMOUNT", numeric, fixedWidth, 16},
	{88, "DEBITS, AMOUNT", numeric, fixedWidth, 16},
	{89, "DEBITS, REVERSAL AMOUNT", numeric, fixedWidth, 16},
	{90, "ORIGINAL DATA ELEMENTS", numeric, fixedWidth, 42},
	{91, "FILE UPDATE CODE", textual, fixedWidth, 1},
	{92, "FILE SECURITY CODE", textual, fixedWidth, 2},
	{93, "RESPONSE INDICATOR", textual, fixedWidth, 6},
	{94, "SERVICE INDICATOR", textual, fixedWidth, 7},
	{95, "REPLACEMENT AMOUNTS", textual, fixedWidth, 42},
	{96, "MESSAGE SECURITY CODE", hexBin, fixedWidth, 8},
	{97, "AMOUNT, NET SETTLEMENT", textual, fixedWidth, 17},
	{98, "PAYEE", textual, fixedWidth, 25},
	{99, "Settlement institution Id code", numeric, llVar, 11},
	{100, "RECEIVING INSTITUTION IDENT CODE", numeric, llVar, 11},
	{101, "FILE NAME", textual, llVar, 17},
	{102, "ACCOUNT IDENTIFICATION 1", textual, llVar, 28},
	{103, "ACCOUNT IDENTIFICATION 2", textual, llVar, 28},
	{104, "Transaction description", textual, lllVar, 100},
	{105, "Reserved for ISO use", textual, lllVar, 999},
	{106, "Reserved for ISO use", textual, lllVar, 999},
	{107, "Reserved for ISO use", textual, lllVar, 999},
	{108, "Reserved for ISO use", textual, lllVar, 999},
	{109, "Reserved for ISO use", textual, lllVar, 999},
	{110, "Reserved for ISO use", textual, lllVar, 999},
	{111, "Reserved for ISO use", textual, lllVar, 999},
	{112, "Reserved for ISO use", textual, lllVar, 999},
	{113, "Reserved for ISO use", textual, lllVar, 999},
	{114, "Reserved for ISO use", textual, lllVar, 999},
	{115, "Reserved for ISO use", textual, lllVar, 999},
	{116, "Reserved for ISO use", textual, lllVar, 999},
	{117, "Reserved for ISO use", textual, lllVar, 999},
	{118, "RESERVED NATIONAL USE", textual, fixedWidth, 10},
	{119, "RESERVED NATIONAL USE", textual, fixedWidth, 10},
	{120, "RESERVED PRIVATE USE", textual, lllVar, 999},
	{121, "RESERVED PRIVATE USE", textual, lllVar, 999},
	{122, "RESERVED PRIVATE USE", textual, lllVar, 999},
	{123, "RESERVED PRIVATE USE", textual, lllVar, 999},
	{124, "RESERVED PRIVATE USE", textual, lllVar, 999},
	{125, "RESERVED PRIVATE USE", textual, lllVar, 40},
	{126, "RESERVED PRIVATE USE", textual, lllVar, 999},
	{128, "MAC EXTENDED", binary, fixedWidth, 32},
}

// zoneSub127 is the DE 127 subfield group: a binary sub-bitmap over subfields
// 2..42.
var zoneSub127 = subPackager{
	id:     "zone-127",
	name:   "RESERVED PRIVATE USE",
	bitmap: fieldcodec.BitmapBinary,
	fields: []field{
		{2, "SWITCH KEY", textual, llVar, 32},
		{3, "ROUTING INFORMATION", textual, fixedWidth, 48},
		{4, "POS DATA", textual, fixedWidth, 22},
		{5, "SERVICE STATION DATA", textual, fixedWidth, 73},
		{6, "AUTHORIZATION PROFILE", numeric, fixedWidth, 2},
		{7, "CHECK DATA", textual, llVar, 50},
		{8, "RETENTION DATA", textual, lllVar, 999},
		{9, "ADDITIONAL NODE DATA", textual, lllVar, 255},
		{10, "CVV2", numeric, fixedWidth, 3},
		{11, "ORIGINAL KEY", textual, llVar, 32},
		{12, "TERMINAL OWNER", textual, llVar, 25},
		{13, "POS GEOGRAPHIC DATA", textual, fixedWidth, 17},
		{14, "SPONSOR BANK", textual, fixedWidth, 8},
		{15, "AVS REQUEST", textual, llVar, 29},
		{16, "AVS RESPONSE", textual, fixedWidth, 1},
		{17, "CARDHOLDER INFORMATION", textual, llVar, 50},
		{18, "VALIDATION DATA", textual, llVar, 50},
		{19, "BANK DETAILS", textual, fixedWidth, 31},
		{20, "AUTHORIZER DATE SETTLEMENT", numeric, fixedWidth, 8},
		{21, "RECORD IDENTIFICATION", textual, llVar, 12},
		{22, "STRUCTURED DATA", textual, lllllVar, 99999},
		{23, "PAYEE NAME AND ADDRESS", textual, fixedWidth, 253},
		{24, "PAYER ACCOUNT INFORMATION", textual, llVar, 28},
		{25, "ICC DATA", textual, llllVar, 9999},
		{26, "ORIGINAL NODE", textual, llVar, 20},
		{27, "CARD VERIFICATION RESULT", textual, fixedWidth, 1},
		{28, "AMERICAN EXPRESS CARD IDENTIFIER", numeric, fixedWidth, 4},
		{29, "3-D SECURE DATA", hexBin, fixedWidth, 40},
		{30, "3-D SECURE RESULT", textual, fixedWidth, 1},
		{31, "ISSUER NETWORK ID", textual, llVar, 11},
		{32, "UCAF DATA", textual, llVar, 33},
		{33, "EXTENDED TRANSACTION TYPE", numeric, fixedWidth, 4},
		{34, "ACCOUNT TYPE QUALIFIERS", numeric, fixedWidth, 2},
		{35, "ACQUIRER NETWORK ID", textual, llVar, 11},
		{36, "CUSTOMER ID", textual, lllVar, 999},
		{37, "EXTENDED RESPONSE CODE", textual, lllVar, 999},
		{38, "ADDITIONAL POS DATA CODE", textual, lllVar, 999},
		{39, "ORIGINAL RESPONSE CODE", textual, lllVar, 999},
		{40, "ACCOUNT TYPE QUALIFIERS", textual, lllVar, 999},
		{41, "ORIGINATING REMOTE ADDRESS", textual, lllVar, 999},
		{42, "TRANSACTION NUMBER", textual, lllVar, 999},
	},
}

// Zone returns the "zone" packager profile.
func Zone() *iso8583.Schema { return zonePackager.schema() }
